# Generated by Django 5.0.3 on 2024-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название версии'),
        ),
    ]
