# Generated by Django 5.0.3 on 2024-05-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit_published', 'Может менять опубликованность продукта'), ('can_edit_description', 'Может редактировать описание продукта')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
