# Generated by Django 5.0.3 on 2024-05-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit_published', 'Может менять опубликованность блога')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
