# Generated by Django 5.0.3 on 2024-04-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_changed',
            new_name='updated_at',
        ),
    ]
