# Generated by Django 5.0.3 on 2024-05-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
