# Generated by Django 5.0.3 on 2024-05-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options_product_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_published', 'Может менять опубликованность продукта'), ('can_edit_description', 'Может редактировать описание продукта'), ('can_edit_category', 'Может редактировать категорию продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
